import './globals.css';
import { Inter } from 'next/font/google';
import { Footer } from '~/components/Footer';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} dark`}>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
