import '../styles/index.css';
import { ReactNode } from 'react';
import { Inter } from 'next/font/google';
import { Footer } from '~/components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
